version: '3'

services:
  postgres:
    image: postgres:10.12
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    ports:
        - "5432:5432"

  elasticsearch:
    image: elasticsearch:7.8.0
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"